name: ml
channels:
  - conda-forge
  - damianavila82
dependencies:
  - python==3.6 # We have to use 3.6 because of nbgrader
  - cython
  - dataclasses
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - mlxtend
  - nbgrader
  - numpy
  - pandas 
  - seaborn
  - scikit-learn
  - scipy
  - requests
  - rise
  - pip:
    - dit
    - dtreeviz

 

    
